### PR TITLE
Create app theme

### LINKED ISSUE #46: Use different Primary and Secondary Colors
As recommended by Francisco, we should avoid using the colors Green and Yellow, since they are used as an information, we should follow the color palette created for VOST

https://drive.google.com/file/d/1qLIXjp_nSWs8kpMdLFcNj9NQvxNyBsCb/view

We need to find proper Material colors that fit well with the VOST palette of Blue and that are inclusive.
Then update the project with the new colors.

### PR DESCRIPTION
**Pull request by diegoalvis**
FIx #46 Create the app theme to define the colors scheme.

### CODE REVIEW

**Review by OldMetalmind — APPROVED** [review]

**Comment by OldMetalmind** [comment]
@Vanethos can you help understand why Travis build is failing.

**Review by Vanethos — APPROVED** [review]

**Comment by Vanethos** [comment]
@OldMetalmind this has to be something with the configuration of Travis, not this PR itself.

At the moment Android is being built, while iOS is having an error configuring the project.

So, if you want, you can merge this pull request

**Comment by diegoalvis** [comment]
Probably you need to perform a pod repo update before building ios
`cd ios && pod repo update`

**Comment by OldMetalmind** [comment]
I've approved the merge and lets create an issue regarding the iOS build

**Pull request closed without merging**
